# really advise to have mamba installed on top of conda.
#
# create environment:
#   > mamba env create -f environment.yml
# update environment:
#   > mamba env update -n yt-player --file environment.yml --prune
# activate with conda:
#   > conda activate yt-player
# deactivate:
#   > conda deactivate

name: yt-player
channels:
- conda-forge
- postelrich
- travis
dependencies:
- python=3.9
- pip
- python-levenshtein
- yt-dlp==2023.09.24
# developer dependencies
- black
- isort
- flake8
- pandas
- regex
- pyment
# - ffprobe
- ffmpeg
# - unidecode
# pip dependencies
- pip:
    - python-vlc