# really advise to have mamba installed on top of conda.
#
# create environment:
#   > mamba env create -f environment.yml
# update environment:
#   > mamba env update --file environment.yml --prune
# activate with conda:
#   > conda activate yt-player
# deactivate:
#   > conda deactivate

name: yt-player
channels:
- conda-forge
- postelrich
dependencies:
- python=3.9
- yt-dlp
- pip
# developer dependencies
- black
- isort
- flake8
- pandas
# pip dependencies
- pip:
    - python-vlc